### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by RevolutionServidores** [DeadP4xel/SealDrop-KOTH#1]
Good day,

First congratulations for the great job, try to run on my dedicated server and the service in this crash, I do not know if you have connection with the upgrade.

Thank you

**Comment by DeadP4xel** [comment]
Hello,
can you send me your latest logfiles ?

Please check your extdb-conf.ini for correct mysql-parameters.

**Comment by RevolutionServidores** [comment]
I am sending a print of Crash, I have Visual Studio C ++ 2010 and 2013 installed.

Crash

http://prntscr.com/99x3ms

Log

http://pastebin.com/Eem1mFnu

Thank you for support.

**Comment by DeadP4xel** [comment]
I will release a patch in the next hour this will support extDB <67 and >68. Then it will work.
