### ISSUE TITLE
Porting to a new map

### ISSUE THREAD

**Issue by ShineT0T** [DeadP4xel/SealDrop-KotH#10]
Hallo DeadP4xel,

Nachdem wir deine mod erfolgreich auf Altis getestet haben, würden wir das ganze gerne etwas modifizieren und auf eine neue Map portieren. Leider lässt deine Lizenz das so aber nicht zu. 
Momentan sind wir noch tief in der Testphase, daher gibt es dort noch keine Überschneidungen. Wäre Super wenn wir deine Erlaubnis bekommen würden. Selbstverständlich würden wir dir Credits geben.

bisherige Anpassungen: - mission.sqf (Zonen an die richtigen Stellen gemoved etc) - gui.hpp (rm: Sealdrop Text [sry aber das ist zu viel], KD Ratio [unwichtig], generell kleiner designed

Leider finde ich aber das Airdrop script nicht, und momentan landet der völlig in den Kapaten. Theoretisch müsste der doch in der Functions.h auftauchen? Nunja evntl finden wir das auch selbst, dennoch wäre ein wenig Hilfe sicher willkommen ;)

 to do: - time in zone->points
           - Airdrop Positionen anpassen
           - add Jets to Shops, Jetspawns
           - make CUP Weapons and Vehicles anvailabe in Shops
           - mehr Anpassungen folgen

Mfg ShineT0T

**Comment by ShineT0T** [comment]
nevermind, wir bauens selbst. Dank Eden ist das ja jetzt etwas übersichtlicher.

**Comment by DoubleX77** [comment]
I'd like that, send me :)
