### ISSUE TITLE
Update Eden?

### ISSUE THREAD

**Issue by Lionscrest** [DeadP4xel/SealDrop-KotH#11]
Hallo wolte mal fragen ob es die mission auch für das neue arma update geben wird oder nicht 
die mission kann man nicht mit der neuen version updaten 

MFG

**Comment by DeadP4xel** [comment]
Hallo,

der Patch dazu kommt heute. Bin bereits dran.

**Comment by Lionscrest** [comment]
Danke Dir für die Info

Wollte noch fragen kommen da andere Stätte noch dazu wird die map noch weiter bearbei?tet
kommt noch ein lock system noch bei??

**Comment by DeadP4xel** [comment]
Momentan ist nur Kavala vorgesehen. Aber die Zukunft kann alles bringen.
