### ISSUE TITLE
abandoned?

### ISSUE THREAD

**Issue by DoubleX77** [DeadP4xel/SealDrop-KotH#15]
the author will continue to support the mod?

**Comment by Soloknight** [comment]
I hope so, just waiting on a few fixes to run it full time

**Comment by DeadP4xel** [comment]
Of course I still work on the mod. I will check the issues today..

**Comment by DoubleX77** [comment]
I can make any changes in the mod? you authorize?

**Comment by DeadP4xel** [comment]
You can open a pull request. But at the moment I won't give someone the authorization.

**Comment by DoubleX77** [comment]
more I can edit to put on my server?

**Comment by N4mEL3sS** [comment]
You are allowed to edit the mod on your server as long as you give credits to DeadP4xel and Sealdrop, don't remove him from the description.ext as the author!
