### ISSUE TITLE
server crashing

### ISSUE THREAD

**Issue by numpty9989** [DeadP4xel/SealDrop-KotH#18]
i followed the install intructions  fully but on loading server it crashes saying arma 3 is not responding

only happens on loading this but if try to run any other server works fine plz help no errors in RPT

**Comment by N4mEL3sS** [comment]
Do you get this error on your client side or does the server give you that error.

**Comment by numpty9989** [comment]
the server does

**Comment by numpty9989** [comment]
i have tried it with stock arma3server.exe and one supplied

**Comment by N4mEL3sS** [comment]
I'll try to help you. Add me on skype: n4mel3ss_
