### ISSUE TITLE
SQL Player data reset

### ISSUE THREAD

**Issue by breaup** [DeadP4xel/SealDrop-KotH#19]
When mission restart and I rejoin right away by the server it stay stuck on getting player information by server, then If I quit and come back the player account is reset in the database back to 0. 

I check the server side RPT and I am getting this:

`Error in expression <private["_uid","_side","_player"];

if(sd_clientLoad) exitWith {};

_player 	=>
  Error position: <sd_clientLoad) exitWith {};

_player 	=>
  Error Undefined variable in expression: sd_clientload
File mpmissions\__cur_mp.Altis\database\fn_sendData.sqf, line 11`

This is my send data

/*
	File: fn_sendData.sqf
	Author: DeadP4xel

	Description:
	Send Player stats to server
*/
private["_uid","_side","_player"];

// ERROR CHECK
if(sd_clientLoad) exitWith {};

// GET DATA
_player 	= player;
_side 		= side _player;
_uid 		= getPlayerUID _player;

// PLAYER SCREEN
0 cutText[format[localize "STR_Script_GINFO",profileName],"BLACK FADED"];
0 cutFadeOut 9999999;

// SEND DATA TO SERVER
[[_uid,_side,_player],"DB_fnc_getData",false,false] spawn BIS_fnc_MP;

**Comment by DeadP4xel** [comment]
Hey,

can you send me your latest RPT logfile and the extDB log too?

**Comment by breaup** [comment]
EXTDB http://pastebin.com/xjmXgsRD

RPT http://pastebin.com/dj7XZYeZ

**Comment by breaup** [comment]
I wonder if its a mysql issue, I did another test and 3 times it took before my player data was wipe. I did again then took 2 #restart then it did the same thing.
