### ISSUE TITLE
Player Getting Information From Player: Player Name

### ISSUE THREAD

**Issue by wesleymoura** [DeadP4xel/SealDrop-KOTH#2]
I'm all done, like the life of servers, but using the KOTH information following the tutorial and am getting stuck in the player getting information screen.

I'll leave the RPT TADST, DB Screen image and the image with the Config extdb.

I'm did something wrong or that some file will be giving this it?

RPT: http://pastebin.com/xXiCgaK5

Extdb-confg.ini: http://pastebin.com/v2EAwmSk

Black Screen: http://prntscr.com/9ae5k9

PS: He gets to create the User DB in the table players, however not out of the screen
http://prntscr.com/9ae5z0

**Comment by DeadP4xel** [comment]
I uploaded a new version. Please try it again.

**Comment by wesleymoura** [comment]
Same problem, but if I give Esc and give Respawn I can play normal appears the intro screen and huds and I can play.

**Comment by DeadP4xel** [comment]
https://github.com/DeadP4xel/SealDrop-KOTH/commit/f1f7626b645f298d9a6e2b0cc6d7664c7a02e06d
Fixed
