### ISSUE TITLE
MSVCP100.dll fehlt

### ISSUE THREAD

**Issue by niconowy** [DeadP4xel/SealDrop-KOTH#4]
Hi.

Ich habe denn Fehler MSVCP100.dll fehlt. Ich habe sie eingefügt aber es geht trotzdem nicht.

Danke!

**Comment by DeadP4xel** [comment]
Hallo,

ich werde das mal prüfen.

**Comment by Angrygargamel** [comment]
wie wärs wenn du mal deine nötigen vcredist installierst anstatt da einzelne dll files hin und her zu kopieren?
