### ISSUE TITLE
Merory dump

### ISSUE THREAD

**Issue by Soloknight** [DeadP4xel/SealDrop-KOTH#5]
I would love to test this mod out but I keep getting 

  A3_Modules_F_UAV in a3\modules_f\uav\, A3_Plants_F_Bush in a3\plants_f\bush\
  A3_Weapons_F_Acc in a3\weapons_f\acc\
Mods: @kothServer
Extensions:
  date (x:\xxxx\axxxxx\@kothServer\date.dll) [] []
  extDB2 (x:\xxxxxxx\xxxxxxxx\@kothServer\extDB2.dll) [67.0.0.0] [67.0.0.0]
Distribution: 0
Version 1.54.133741
Fault time: 2016/01/15 07:45:30
Fault address:  75345B68 01:00014B68 C:\Windows\SYSTEM32\KERNELBASE.dll
file:     KOTH_SD (__cur_mp)
world:    Altis
Prev. code bytes: 75 1F 21 4C 24 10 8D 04 24 50 FF 15 2C 63 3F 75
Fault code bytes: 8B 4C 24 54 33 CC E8 41 91 FF FF 8B E5 5D C2 10

Registers:
EAX:023E7B30 EBX:36DC21A1
ECX:00000003 EDX:00000000
ESI:6F5366FC EDI:023E7BDC
CS:EIP:0023:75345B68
SS:ESP:002B:023E7B30  EBP:023E7B8C
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00200216
=======================================================
note: Minidump has been generated into the file x:\xxxx\xxxxxxxx\@kothServer\arma3server1_2016-01-15_07-45-12.mdmp

**Comment by DeadP4xel** [comment]
Which version of extDB2 do you use ?

**Comment by Soloknight** [comment]
67 and 70 both same results

On Sat, Jan 16, 2016 at 7:56 AM, DeadP4xel <notifications@github.com> wrote:

> Which version of extDB2 do you use ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DeadP4xel/SealDrop-KOTH/issues/5#issuecomment-172203668>
> .
>



-- 
Christopher Mitchell
Phone: 812-290-3683

**Comment by Soloknight** [comment]
Ok got it fixed, anyway to make the ui smaller? in a config file
